### ISSUE TITLE
Platforms in level 2 do not react to weight

### ISSUE THREAD

**Issue by rayrase** [rayrase/potentially-dangerous#20]
Currently, the platforms respond like regular platforms and do not react when dropping an item or putting the weight of the player on them. 

**DEPENDENCY**: We must fix detection of weight on platforms -> Issue #1

**Comment by metaspy** [comment]
Tyler updated the dependant platforms to react to each others weight - I have fixed a rounding error that would move pair up faster than current platform moved down
