### ISSUE TITLE
Item interact() causes the image to flicker from on/off states

### ISSUE THREAD

**Issue by rayrase** [rayrase/potentially-dangerous#3]
The image constantly switches from on/off states.

It might have something to do with 

`self.activated = not self.activated`

or it could also be an issue with the implementation of interacting on collision.

**Comment by metaspy** [comment]
problem was that the switch was sitting on top of the spike trap and was looking for an attribute of "collectible" which all items have, just are turned false - so the switch was merrily flipping on and off.
