### ISSUE TITLE
Door opens when interacting even if switch is neccessary

### ISSUE THREAD

**Issue by rayrase** [rayrase/potentially-dangerous#5]
This might not be an issue when connection is implemented. Opened the issue just in case.

Information: Player interacts with Q

**Comment by metaspy** [comment]
why the hell does a player interact with Q?

**Comment by metaspy** [comment]
I just beat lvl 1 - this is working

**Comment by rayrase** [comment]
Thank you for closing these issues Chad! My apologies about the interaction button, I will take care of changing it back to E. I wanted to quickly test the door interaction.
